---
- hosts: dev
  become: True
  tasks:
    - name: Install python pip
      yum:
        name: python-pip
        state: present
    - name: Install docker python module
        pip:
          name: docker-py
          state: present
    - name: Start container 
        docker_container:
           name: testcontainer
           image: "966145/myimagnov:${DOCKER_TAGi}"
           state: started
           published_ports:
             - 0.0.0.0:8080:80
